/* introductionLines.ts */
const introductionLines = [
"What is this?",
"a website that makes custom resumes using your own words",
"",
"Keep your profile current. Paste a job ad whenever. Get a tailored resume in 5 seconds.",
"",
"Why",
"toil sucks toil when you need $ to live sucks more the world is full of a bunch of fake jobs adverts that you have to get past to find real opportunities",
"",
"Where are we at",
"I've recorded my idea - ./ResuMeisterv6.png",
"I've made a resume generator that uses text documents and glues them together. It's cute but flawed like me.",
"I'm making a website",
"Alright... I'll bite - tell me more",
"Okay so - you apply for a job. You hear nothing. You apply for 10 jobs. Crickets. You try to do it faster. You apply for 1000 jobs. Nada.",
"",
"Maybe you're the problem.",
"",
"You're not working hard enough.",
"",
"You're not enough.",
"",
"You feel self concious.",
"",
"That's no good. You pull yourself out of it.",
"",
"Maybe you just need to put more work in.",
"",
"You tailor it for every application.",
"",
"You apply for 10 jobs every day but you put an hour into each application.",
"",
"You are no longer a human being with needs and value and worth.",
"",
"You are a job application machine in a cruel world.",
"",
"You start to get results! You start to get interviews!!",
"",
"Some of them are horrible... you can see why they were looking.",
"",
"They're bad. And you're still not getting many hits.",
"",
"You find out about fake jobs ads. How can you possibly compete.",
"",
"You need something. You use a free AI website. It makes resumes for you. They look amazing. This is going to work.",
"",
"They have all the keywords. They're perfect. They are kinda bullshitting - but at this point but who cares.",
"",
"You get 0 hits.",
"",
"None.",
"",
"They're going in the bin. The company has it's own AI and it could see you coming a mile away. It knew you cheated.",
"",
"You can't win.",
"",
"You go back to the 10 hour days. You do it all manually.",
"",
"You're running low.",
"",
"You're getting desperate.",
"",
"You're amazing... but you settle. You've found a job. It's okay. You could do better.",
"",
"Fuck that. I've got a better plan - just trust me.",
"Tell me all your skills - write it like it's lines on a resume",
"",
"Tell me all your experience",
"",
"Tell me all your hobbies - max three words each - :)",
];

export default introductionLines;